# Generated by Django 2.0 on 2017-12-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('location', models.FileField(upload_to='files/')),
            ],
        ),
    ]
