# Generated by Django 2.0 on 2017-12-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
