# Generated by Django 2.0 on 2017-12-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_files_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
        migrations.RemoveField(
            model_name='files',
            name='path',
        ),
    ]
